@startuml

class Naveheroe 
class naveenemiga
class bichos
class dispara   
class matar 
class ganar 
class perder 
    Naveheroe --o dispara
    dispara --o naveenemiga
    dispara --o bichos
    naveenemiga --o dispara
    dispara --o Naveheroe

@enduml